name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to deploy'
        required: false
        default: ''
  workflow_run:
    workflows: [Build]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version
        if: ${{ ! contains(inputs.version, '.') }}
        id: latest
        uses: gregziegan/fetch-latest-release@v2.0.0
      - name: Resolve version
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ ! contains(inputs.version, '.') }}
          if_true: ${{ steps.latest.outputs.name }}
          if_false: ${{ inputs.version }}
      - uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ steps.version.outputs.value }}
          fileName: "blog-*.zip"
          tarBall: false
          zipBall: false
          extract: false
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment for ${{ steps.version.outputs.value }}
        id: deployment
        with:
          token: ${{ secrets.PAT }}
          description: ${{ steps.version.outputs.value }}
          environment: production
      - name: Upload release ${{ steps.version.outputs.value }} to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: blog-${{ steps.version.outputs.value }}.zip
          target: /srv/
      - name: Upload release ${{ steps.version.outputs.value }} to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /srv
            unzip blog-${{ steps.version.outputs.value }}.zip -o -d blog-${{ steps.version.outputs.value }}/
            rm blog
            rm blog-*.zip
            ln -s blog-${{ steps.version.outputs.value }} blog
            service nginx reload
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.PAT }}
          environment-url: https://jamiehurst.co.uk
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.PAT }}
          environment-url: https://jamiehurst.co.uk
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
